### ISSUE TITLE
【BUG】PDF拖拽至白板或笔记的实体没有文本内容，及删除实体后有残留

### ISSUE THREAD

**Issue by holduan** [Rendevoz/Rendevoz#10]
如题

白板：
[[SHANA]2023.08.29_18-33-45.951.webm](https://github.com/Rendevoz/Rendevoz/assets/80377040/014ecc0c-c693-4bd9-9d41-bf590362f81a)

笔记：
[[SHANA]2023.08.29_18-36-57.255.webm](https://github.com/Rendevoz/Rendevoz/assets/80377040/47371dfa-a96d-45fc-93c5-0fe4951a5eb6)

**Comment by RealRong** [comment]
这个问题已于下个版本中修复，如果在设置=》组件=〉标注中选择显示原文，那么名称就会说unnamed label。
不过下个版本会显示原文了

**Comment by holduan** [comment]
> 

嗯嗯，不过如果标注不需要添加标题，多个“Unnamed PDF label”体验不好，原文跟标题的展示和编辑交互还得考虑考虑

![image](https://github.com/Rendevoz/Rendevoz/assets/80377040/49c397cc-6422-4c2d-9db2-bfab9f2aac66)

**我想到的一个方案是：默认只展示原文，右键计入编辑状态后，同时展示“原文编辑框”和“标题填写框”**

---
还有就是节点顶部的信心可以改到下面
![image](https://github.com/Rendevoz/Rendevoz/assets/80377040/a8759654-9590-4c5b-8e99-63803ef8054f)

**Comment by holduan** [comment]
> 这个问题已于下个版本中修复，如果在设置=》组件=〉标注中选择显示原文，那么名称就会说unnamed label。 不过下个版本会显示原文了

嗯嗯，不过如果标注不需要添加标题，多个“Unnamed PDF label”体验不好，原文跟标题的展示和编辑交互还得考虑考虑

![image](https://github.com/Rendevoz/Rendevoz/assets/80377040/49c397cc-6422-4c2d-9db2-bfab9f2aac66)

**我想到的一个方案是：默认只展示原文，右键计入编辑状态后，同时展示“原文编辑框”和“标题填写框”**

---
还有就是节点顶部的信心可以改到下面
![image](https://github.com/Rendevoz/Rendevoz/assets/80377040/a8759654-9590-4c5b-8e99-63803ef8054f)
