### ISSUE TITLE
希望视频标注笔记可以在视频播放时悬浮在视频上显示，就像弹幕一样，并且可以调整显示时长和开始显示时间，以及调整位置和大小，还有背景颜色

### ISSUE THREAD

**Issue by muhanstudio** [Rendevoz/Rendevoz#106]
希望视频标注笔记可以在视频播放时悬浮在视频上显示，就像弹幕一样，并且可以调整显示时长和开始显示时间，以及调整位置和大小，还有背景颜色

**Comment by KuiyueRO** [comment]
像发弹幕一样发标注！

右侧两个发送键，一个对应章节，一个对应标注，快捷键就enter和ctrl+enter吧
