### ISSUE TITLE
【功能请求】更多的块儿类型

### ISSUE THREAD

**Issue by muhanstudio** [Rendevoz/Rendevoz#135]
希望可以添加更多的块类型，这应该是非常重要的，目前可添加的块儿类型较少，还远远不够用，只有字符，代码，图片，链接，作为一款以块结构为基础的编辑器，希望可以添加更多的块类型，下图是我的建议
![image](https://github.com/Rendevoz/Rendevoz/assets/29907393/4a7dc931-b995-476e-9345-3893251809ad)
目前只有下面的
![image](https://github.com/Rendevoz/Rendevoz/assets/29907393/75d7b0a8-57af-4f5f-af37-ae6462f27aec)

**Comment by muhanstudio** [comment]
目前在我看来，至少还得加个echarts图表，iframe网页，然后就是html块儿，然后就是在文档里预览嵌入其他文档或者实体，以及更多的markdown语法支持
![B27BF0164ACB3F393DBEA662DC40B1CA](https://github.com/Rendevoz/Rendevoz/assets/29907393/d5abc78e-8805-496a-8393-48b29532b929)

**Comment by KuiyueRO** [comment]
还有mermaid也支持下吧，行内思维导图也行
