### ISSUE TITLE
【功能优化】块功能优化

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#143]
允许 块调用组、看板等，对其进行增删改查 的功能
![图片](https://github.com/Rendevoz/Rendevoz/assets/139304871/d446129a-0859-4279-b3e3-464d30bc55f1)

**Comment by 20240227** [comment]
补充一下，这个功能可以在一个页面就能解决大部分问题，不用频繁切换页面，并且排版更自由！希望能采纳，感谢！
