### ISSUE TITLE
【bug】编辑器 - 在特定情况下出现奇怪现象

### ISSUE THREAD

**Issue by 20240227** [Rendevoz/Rendevoz#145]
复现：
选中某块 - 光标从选中的块下方向上移动（键盘） - 按1次回车
这样操作会出现2个块，并且有的块会变成两行的宽度，且编辑两行宽的块时会同步输入另一块（说起来比较复杂，还请看gif）

![20240227_211037](https://github.com/Rendevoz/Rendevoz/assets/139304871/3667e598-1b24-46f1-b4cd-d0cfc0b80f73)

**Comment by 20240227** [comment]
最新复现，光标从选中行的下方，用键盘按键 ↑ （上），使光标移动至选中行行首，再按下回车就会出现bug

https://github.com/Rendevoz/Rendevoz/assets/139304871/dd43edf5-6433-4f81-892b-9e5d168b5acd

**Comment by 20240227** [comment]
最新复现，视频中详细说明了如何复现以及会出现的各种问题，根据测试
不确定是不是 “块” 的相关问题

https://github.com/Rendevoz/Rendevoz/assets/139304871/184ca983-1479-4e07-ab80-b67e55a8bf37

**Comment by RealRong** [comment]
已修复
