### ISSUE TITLE
【功能优化】希望在底部加一个便捷操作栏

### ISSUE THREAD

**Issue by muhanstudio** [Rendevoz/Rendevoz#153]
![image](https://github.com/Rendevoz/Rendevoz/assets/29907393/cf9f6e3f-1b77-41de-a93c-109d829a3180)
希望在界面底部加一个便捷导航栏，可以把Home键，前进后退键，新建实体键，还有搜索键，移到这个栏里面

**Comment by muhanstudio** [comment]
理由：新建实体除了快捷键和页签旁边的加号+，没有找到其他比较显眼的便捷新建入口，另外 Home键，前进后退，搜索，放在视野中央会更好点击并操作，样例图如下
![image](https://github.com/Rendevoz/Rendevoz/assets/29907393/466519ca-6e6f-4944-a36a-f9a83dd998ad)

**Comment by moshangssh** [comment]
支持!!!太需要了
