### ISSUE TITLE
【BUG】有序列表的点会跑到下方

### ISSUE THREAD

**Issue by KuiyueRO** [Rendevoz/Rendevoz#155]
![e9143819e65038e1c379bb63aea4babe](https://github.com/Rendevoz/Rendevoz/assets/63145205/15acb131-5731-4c1c-873f-4cf27f629589)

![a3dc44aea3abbb2ab29e72ae1d99c5c3](https://github.com/Rendevoz/Rendevoz/assets/63145205/96508dab-3c82-43f8-a58a-898462d01772)

**Comment by RealRong** [comment]
已修复
