### ISSUE TITLE
BUG：百度网盘导入内容搜索会空白

### ISSUE THREAD

**Issue by keen0309** [Rendevoz/Rendevoz#16]
BUG：百度网盘导入内容搜索会空白
![image](https://github.com/Rendevoz/Rendevoz/assets/103982843/cd2ecb0c-7c7f-448e-9bd6-6ef67e913da8)

**Comment by RealRong** [comment]
可能原因1:网盘里没有此文件 2:仅支持搜索视频文件，类型不相符 3.网络问题
