### ISSUE TITLE
【新功能】希望能增加柱状图、折线图、曲线图、饼状图视图

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#161]
需求：能把数据以柱状图、折线图、曲线图、饼状图等视图形式呈现
![图片](https://github.com/Rendevoz/Rendevoz/assets/139304871/470ccb5b-ab6c-43df-8aaf-f661083cb72e)

**Comment by muhanstudio** [comment]
这个可以直接引入echarts就可以了，支持嵌入并渲染echarts代码

**Comment by Ihopeyouarehappy** [comment]
> 这个可以直接引入echarts就可以了，支持嵌入并渲染echarts代码

这样的话使用门槛会不会太大了....也不是每个人都会代码的呀，如果可以做的更易于操作会更好吧

**Comment by muhanstudio** [comment]
这个是要考虑工作量的，一个笔记软件，没必要做图表生成器，就连wolai都是放代码的，目前基础编辑器和其他一些笔记的基础硬性功能还没有优化好，这个功能我感觉有点超出范围了，不做的可能性大，应该交给将来的社区插件
可以看看这个issue的进度
https://github.com/Rendevoz/Rendevoz/issues/135
