### ISSUE TITLE
【新功能】希望能增加画板卡片公共标签

### ISSUE THREAD

**Issue by Mao-like** [Rendevoz/Rendevoz#162]
画板页面中，在文件列表栏下增加公共标签或子画板，形成类似双链卡片的效果：

1.一个看板可以不设置公共标签，也可以设置一个公共标签，或者设置多个公共标签；

2.在设置了公共标签的看板中，每个标签列下只会显示同时包含了公共标签和标签列标签的笔记。

**Comment by RealRong** [comment]
没看懂，画板是组里的看板视图吗？
