### ISSUE TITLE
【新功能】用快捷键 实现标签页间的左右跳转 及关闭

### ISSUE THREAD

**Issue by LittleId** [Rendevoz/Rendevoz#164]
作为一个笔记来说，用快捷键来实现标签页间的左右跳转及关闭，应该是挺正常的吧，而且还是用Electron开发的，像浏览器一样，用ctrl+pgup/pgdn实现标签页间的左右跳转、ctrl+w实现关闭标签，对用户来说不用记忆新的使用成本（不止浏览器，很多笔记软件也是这样设置的），而且开发上也不算个难题吧，不知道为啥Rendevoz没加入这个功能，希望可以加入

**Comment by RealRong** [comment]
已支持
