### ISSUE TITLE
[BUG]白板的打组对图片无效

### ISSUE THREAD

**Issue by bingling00** [Rendevoz/Rendevoz#165]
打组后，移动组，图片不跟随

**Comment by RealRong** [comment]
提供一下复现视频

**Comment by bingling00** [comment]
的确很奇怪，我就刚开始的几张图有这个问题，我自己也复现不出来。视频中拖不动的是之前的图片，如果我找到复习的问题了，再跟你说吧

https://github.com/Rendevoz/Rendevoz/assets/61322616/563e08bc-6a51-4b7b-b628-72da8566b467

**Comment by RealRong** [comment]
可能有的图片大小有点问题，重新调整一下大小试试
