### ISSUE TITLE
[BUG]拖动白板里的图片会复制图片

### ISSUE THREAD

**Issue by bingling00** [Rendevoz/Rendevoz#166]
复现方式：
1、点击白板中的图片
2、当图片有蓝色边框了，拖动图片，就会复制出一个新图片

这个图片并不是链接了原图，而是出现一个新的实体

**Comment by RealRong** [comment]
系统限制，没法去溯源你拖拽的图片来自哪里，所以没法链接原图

**Comment by bingling00** [comment]
> 系统限制，没法去溯源你拖拽的图片来自哪里，所以没法链接原图

我描述的可能让你误会了。看下视频吧

https://github.com/Rendevoz/Rendevoz/assets/61322616/36805176-9c10-4d09-b246-b153c822c8fe

选中图片后拖动图片，就不是移动图片了，而是复制图片，并且会变成新的实体
