### ISSUE TITLE
【BUG】：某些从百度导入的视频，在点击播放时，会显示“文件不存在”

### ISSUE THREAD

**Issue by Githiba2013** [Rendevoz/Rendevoz#168]
某些从百度导入的视频，在点击播放时，会显示“文件不存在！”。
如下所示：
![QQ录屏20240303111155](https://github.com/Rendevoz/Rendevoz/assets/149424084/758af8a9-cd67-4e1c-93d0-f51c93e04c68)

但是，这个mp4在下载到本地，并从本地导入到rendevoz后，又是可以正常播放的状态。

**Comment by Githiba2013** [comment]
> 可能是视频长期没播放，网盘在转码，转码完了才能播放，一般等几十秒或者几分钟再打开就好

试了好多次，最后几次等了至少十分钟，还是这样，“文件不存在”。也试过重启rendevoz，还是不行。

**Comment by Githiba2013** [comment]
附上一个符合这种情况的视频：链接：https://pan.baidu.com/s/1_L07Ze47tiAF47Nn-cDFjQ?pwd=1nb8 
提取码：1nb8 
--来自百度网盘超级会员V4的分享

**Comment by RealRong** [comment]
是百度网盘的31066错误，如果还有问题就是网盘自己的问题。
官方文档：https://pan.baidu.com/union/doc/Ql11imcwu

**Comment by Githiba2013** [comment]
> 是百度网盘的31066错误，如果还有问题就是网盘自己的问题。 官方文档：https://pan.baidu.com/union/doc/Ql11imcwu官方文档：https://pan.baidu.com/union/doc/Ql11imcwu

排查了一下网盘文件路径中的特殊符号，发现是不能有“+”号和“&”号，否则会文件不存在。但是我的“每日英语听力”接入百度网盘的时候，是可以正常播放这些路径中有“+”号和“&”号的视频的。
