### ISSUE TITLE
【BUG】: 某些从百度网盘导入的mkv，在选择“导入网盘字幕”的时候，会显示“字幕不存在！”

### ISSUE THREAD

**Issue by Githiba2013** [Rendevoz/Rendevoz#169]
某些从百度网盘导入的mkv，在选择“导入网盘字幕”的时候，会显示“字幕不存在！”。
如下所示：
![QQ录屏20240304195755](https://github.com/Rendevoz/Rendevoz/assets/149424084/5cb2d5f1-ce47-472e-b5a3-01871a06de9e)

但是实际上在百度网盘的同级文件夹中，是有同名字幕的。

**Comment by RealRong** [comment]
网盘字幕导入的是AI字幕，无法导入同文件夹的字幕

**Comment by Githiba2013** [comment]
> 网盘字幕导入的是AI字幕，无法导入同文件夹的字幕

那你有考虑添加“导入同文件夹的字幕”的功能吗？
