### ISSUE TITLE
bug: 重新打开软件的时候，白板上的摘录是拉长的

### ISSUE THREAD

**Issue by chonglin9606** [Rendevoz/Rendevoz#172]
https://github.com/Rendevoz/Rendevoz/assets/47425135/ae7d7c4a-ec22-4434-a9f1-731695e8c9ce

重新打开软件的时候，我如果上次打开的都时候有白板，重新打开的时候白板上的东西会拉长，是个 bug,但是点几下又没了

**Comment by RealRong** [comment]
fixed
