### ISSUE TITLE
bilibili上非集合视频无法订阅，期望增加视频分p功能。

### ISSUE THREAD

**Issue by Heavy233** [Rendevoz/Rendevoz#180]
需求原因：这类视频链接不止一个视频，所以当我看完一个视频自动跳到下一个视频时发现，**标注混乱**的问题。
该部分提供了两种排序，**第一种**是按视频时间排序，一个链接的不同视频记录在同一个时间轴上，所以每个视频的笔记都杂糅在一起，我暂时没有遇到记录时间冲突的情况，但不排除这一可能。**第二种**是按创建时间排序，这种排序似乎可以解决第一种排序的问题，但是事实并非如此。学习知识点的时候并不是一直看到底的，可能会在同一个视频内跳着观看记下标注感想总结，也会在不理解的时候调到前面的视频中观看记录下新的标注，这就导致了按创建时间排序也会让标注变得混乱。
最后希望可以提供解决方法，感谢~

**Comment by Heavy233** [comment]
![1709717618051](https://github.com/Rendevoz/Rendevoz/assets/162428899/43544201-d7e3-42d1-9733-6ac0825a86bb)

遇到的问题
1. 更新之后，之前的标注图片丢失
2. **_点击_** 右侧从上往下数第二个标注：有介质求U sigma1 与sigma2关系 **_3.6的标注_** ，左侧 **_显示_** 的是 **_3.7的进度_**，只有选择正确的集数才对的上，和上面应该是一个问题

**Comment by RealRong** [comment]
对于多p视频，需要把每一p都导进去，比如https://www.bilibili.com/video/BV1qW411H7UX?p=0，https://www.bilibili.com/video/BV1qW411H7UX?p=1，https://www.bilibili.com/video/BV1qW411H7UX?p=2等等。
同时把播放设置里面自动切集关了。
