### ISSUE TITLE
【BUG】在表格下面新建iframe块儿的时候总会跑到表格最后一格里面

### ISSUE THREAD

**Issue by muhanstudio** [Rendevoz/Rendevoz#185]
在表格下面新建iframe块儿的时候，总会跑到表格最后一格里面，其他块儿类型不存在这种情况，只出现于iframe块儿

https://github.com/Rendevoz/Rendevoz/assets/29907393/77b2cc8f-e934-4de2-9f54-caf0f8372069

**Comment by RealRong** [comment]
将于0.9.8修复
