### ISSUE TITLE
视频、PDF标注无法换行

### ISSUE THREAD

**Issue by ygli688** [Rendevoz/Rendevoz#190]
![image](https://github.com/Rendevoz/Rendevoz/assets/97214858/1389b153-7040-4dc5-9dda-1be24334a574)
Enter就退出编辑了，希望可以增加Ctrl + Enter进行换行

**Comment by KuiyueRO** [comment]
软换行是shift+enter

**Comment by ygli688** [comment]
> 软换行是shift+enter

好的感谢，我试了Ctrl和Alt，没有试用Shift，现在可以换行了
