### ISSUE TITLE
【功能建议】快捷键收集

### ISSUE THREAD

**Issue by KuiyueRO** [Rendevoz/Rendevoz#194]
大家快来向群主建议需要哪些快捷键吧🤣🤣🧐🧐

**Comment by muhanstudio** [comment]
新建实体-快捷键
是的，你没有看错，到现在新建实体快捷键都还没有（doge）

**Comment by KuiyueRO** [comment]
- 详情面板快捷键
- 修改面板快捷键
- 样式面板快捷键

**Comment by moshangssh** [comment]
- 空间切换快捷键

**Comment by linyizpx** [comment]
![image](https://github.com/Rendevoz/Rendevoz/assets/160560187/3080b770-2cfc-44cf-9484-d4b4698f4372)
查看信息快捷键

**Comment by linyizpx** [comment]
> 新建实体-快捷键 是的，你没有看错，到现在新建实体快捷键都还没有（doge）

建议新增

**Comment by linyizpx** [comment]
![image](https://github.com/Rendevoz/Rendevoz/assets/160560187/e682960f-e4ed-4746-babf-fa260e4a6b98)
“在新标签中打开”“在侧边栏打开”的快捷键

**Comment by 63847051** [comment]
![{DDE10BCC-5A4C-B588-52C4-EEA68DE09F5D}](https://github.com/Rendevoz/Rendevoz/assets/85275026/b85361cd-3b18-481b-8132-7d74bad4dc4f)
希望可以增加日历时间拖动 实体可以拖动或者自定义时间

**Comment by 63847051** [comment]
希望这个标注拖到白板里有也有悬浮打开的能力
![Uploading 34541EDA89F609D2B2D498C4C0A7F066.png…]()

**Comment by 63847051** [comment]
![Uploading 34541EDA89F609D2B2D498C4C0A7F066.png…]()
希望这个标注拖到白板里有也有悬浮打开的能力

**Comment by Heithon** [comment]
PDF中使用ctrl+滚轮进行放大缩小，就像白板中一样
