### ISSUE TITLE
【BUG】<div class="dock-drop-edge"></div>莫名卡住，导致编辑器区无法点击

### ISSUE THREAD

**Issue by muhanstudio** [Rendevoz/Rendevoz#198]
如图
![H83`5~7J(XE`W09XC02JX$J](https://github.com/Rendevoz/Rendevoz/assets/29907393/897ddea5-9b66-4bd2-980f-771ea6bc1fd1)
视频

https://github.com/Rendevoz/Rendevoz/assets/29907393/98aa7594-860f-4ed1-b316-6b24d0334b47

**Comment by RealRong** [comment]
Fixed
