### ISSUE TITLE
【功能优化】更便捷的 右 侧边栏

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#201]
希望打开侧边栏后，再点击其他位置时会自动关闭侧边栏

![图片](https://github.com/Rendevoz/Rendevoz/assets/139304871/29be3c0d-3d4f-4fc3-b45e-fcd313382ae1)

**Comment by Ihopeyouarehappy** [comment]
据说要像帖子一样顶顶才会被看到（

**Comment by RealRong** [comment]
Fixed
