### ISSUE TITLE
【功能优化】给组添加一个底部的左右滚动条

### ISSUE THREAD

**Issue by muhanstudio** [Rendevoz/Rendevoz#206]
场景：当显示了很多的属性时，横向屏幕已经无法完全展示了，希望在组下面添加一个左右的滚动条，当展示宽带超过视窗时显示滚动条方便拖动查阅

**Comment by muhanstudio** [comment]
![image](https://github.com/Rendevoz/Rendevoz/assets/29907393/2e8b0cd1-d9d8-4c16-b0aa-f495744abbda)

**Comment by muhanstudio** [comment]
![image](https://github.com/Rendevoz/Rendevoz/assets/29907393/e0f34468-7d56-431f-8734-2357459ad7d5)

**Comment by muhanstudio** [comment]
刚刚发现，内嵌到文档的数据库是有这个滚动条的，但是单独打开却没有
![image](https://github.com/Rendevoz/Rendevoz/assets/29907393/7e33d4d9-220d-4ef6-ae0d-cb2e1c7b02bc)

**Comment by RealRong** [comment]
有啊，第二张图下面不就是一个灰色的滚动条吗

**Comment by muhanstudio** [comment]
> 有啊，第二张图下面不就是一个灰色的滚动条吗

这个滚动条只在嵌入文档的组中显示，单独打开是没有的

**Comment by muhanstudio** [comment]
我的原因，配色问题没看到第一张图下面也是有浅色滚动条的，closed了

**Comment by muhanstudio** [comment]
![image](https://github.com/Rendevoz/Rendevoz/assets/29907393/7a45b12d-a4f4-4876-8ad2-6319fe1e18f8)
