### ISSUE TITLE
【功能优化】自定义程度更高的 左 侧边栏

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#207]
希望左侧边栏上方的图标也可以加入右键“显示与隐藏”，同时启动软件时恢复上次侧边栏情况（打开与否，打开了哪个板块），这样就不用每次都要手动点开侧边栏，再选择要打开的板块

![图片](https://github.com/Rendevoz/Rendevoz/assets/139304871/f18ecdbd-b73d-415d-8641-025856f60cbc)

**Comment by Eduna2021** [comment]
赞同

**Comment by Ihopeyouarehappy** [comment]
R大看我（
