### ISSUE TITLE
【Bug】白板连接线漂移，布局混乱

### ISSUE THREAD

**Issue by Heithon** [Rendevoz/Rendevoz#208]
白板重新打开后，连接线脱离了实体，向右边平移了，并且每打开一次就平移一次

打开几次后：
![image](https://github.com/Rendevoz/Rendevoz/assets/85172139/1f8c47c6-b06d-4212-b7ca-e383f57b8677)
再打开一次：
最右边的已经出界了
![image](https://github.com/Rendevoz/Rendevoz/assets/85172139/a99884b4-d13a-4838-a805-3242b7e91681)

**Comment by RealRong** [comment]
Fixed
