### ISSUE TITLE
【编辑器】【优化】在块中嵌入组时的显示问题

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#213]
图1 为块中嵌入组的正常显示效果
图2 为拖动分割线，改变嵌入块大小后视图选项卡显示不全的效果，如果继续缩小，视图选项卡（表格）会完全被挡住
图3 为希望改进的效果，缩小到显示不全时把视图选项卡往上移一行（其实应该是除了视图选项卡以外的都往下移才对？）

![20240320](https://github.com/Rendevoz/Rendevoz/assets/139304871/f6f89c45-d94f-4244-bdc9-9b63906e6043)
![20240320_1](https://github.com/Rendevoz/Rendevoz/assets/139304871/d0f9530f-6a1a-4c75-a8d2-b59aabac7efd)
![20240320_2](https://github.com/Rendevoz/Rendevoz/assets/139304871/0cec0c83-631a-4830-a939-209c12915228)

**Comment by RealRong** [comment]
Supported
