### ISSUE TITLE
【优化】【标签页】标签页拖动的优化

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#219]
现状：
标签页拖动到同屏时，必须拖至现有标签页处，操作不够丝滑

希望改进：
把标签页拖至同屏 “标签页栏” 时即可完成标签页拖动

https://github.com/Rendevoz/Rendevoz/assets/139304871/9b2d5a76-e5df-48c9-bfc7-4cfa42416833

**Comment by RealRong** [comment]
Supported
