### ISSUE TITLE
【BUG】订阅内容页点击右上角三个点会直接crush

### ISSUE THREAD

**Issue by muhanstudio** [Rendevoz/Rendevoz#221]
Uploading QQ2024324-112429-HD.mp4…

稳定复现一个crush，订阅https://rsshub.app/natgeo/dailyphoto，打开任意一篇文章，然后点击右上角...就会crush，非订阅特性，任何一个订阅，但凡点击那里都会直接炸

**Comment by RealRong** [comment]
Fixed
