### ISSUE TITLE
【优化】表格最小列宽的调整优化

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#222]
现状：
表格列宽过宽，勾选框占用过多空间，做 toso 不方便

希望改进：
把表格最小列宽缩小些，这样更节省空间，求求

![ab6cbe77b6e99310673ef81e7e90ae1b](https://github.com/Rendevoz/Rendevoz/assets/139304871/7ba4fef5-4c52-447e-bf06-c78223faa5f4)

**Comment by RealRong** [comment]
Fixed
