### ISSUE TITLE
【BUG】给内容添加链接时粘贴的链接会多出 http

### ISSUE THREAD

**Issue by moshangssh** [Rendevoz/Rendevoz#223]
![bug](https://github.com/Rendevoz/Rendevoz/assets/58763445/35aa2094-d045-4381-a371-3149bce42125)

**Comment by RealRong** [comment]
Fixed

**Comment by moshangssh** [comment]
> Fixed

没修复呀,在中文输入法下面还是有这个问题,我用的微软输入法
