### ISSUE TITLE
【BUG？】【优化】新建实体时没有自动设置筛选信息

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#225]
现状：
1）新建实体需要手动选择实体类型，操作非常繁琐不便
2）如果有筛选条件，新建实体后不会显示新建的实体，需要在其他无筛选的表格中设置，操作非常繁琐不便
3）新增实体时貌似有一点点卡顿、延迟？

期望优化：
1）新增 “新建实体类型” 的默认设置
2）如果有筛选条件，新建实体时会自动填写筛选条件信息
3）优化新建实体时的效率

https://github.com/Rendevoz/Rendevoz/assets/139304871/b243967d-0522-454a-ac02-ae9b054fd13a

**Comment by RealRong** [comment]
Supported
