### ISSUE TITLE
【bug】实体内描述文字的显示/隐藏状态不会被记住

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#226]
现状：
实体内的描述文字 显示/隐藏 状态不会被记住，关闭标签页或软件后再次打开实体，描述文字需要再次手动点击才能展示

希望修复：
每次点击 显示/隐藏 描述时记住该状态

https://github.com/Rendevoz/Rendevoz/assets/139304871/8a945000-8522-44af-bce8-fde00a62f8f1

**Comment by RealRong** [comment]
已修复
