### ISSUE TITLE
【bug】【优化】问题类型实体的内容没有显示块的操作

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#227]
现状：
问题类型实体 中的文本无法操作块，没有显示块左侧的 “ + ” 和 “ 六个点 ”

希望优化：
增加块左侧的两个按钮

https://github.com/Rendevoz/Rendevoz/assets/139304871/b04497be-1156-442e-b5aa-f89e6875cf58

**Comment by RealRong** [comment]
设计如此
