### ISSUE TITLE
【新功能需求】关系图谱根据来源分组，并做更多的样式区别

### ISSUE THREAD

**Issue by holduan** [Rendevoz/Rendevoz#23]
效果如**图1**，在分组后关系更加直观。
出发点：PDF、网页、视频标注的来源链接实用性低，不展示会让关系图谱看起来更整洁。但存在一堆节点出自同一个地方，散开又不利于展示彼此的关系，像书籍PDF，因此建议做一下分组聚拢。
**图2**的效果明显不如**图1**。

`自动产生的链接`应该与`非自动产生的链接`在属性上有区别，这样过滤条件就又多了一个 😋

另外，被链接到的链接越多，图标越大。

**图1**：
![image](https://github.com/Rendevoz/Rendevoz/assets/80377040/d2ba20fa-d548-4623-a1df-55bb672aa80c)

**图2**：
![image](https://github.com/Rendevoz/Rendevoz/assets/80377040/3e2681db-7328-4f67-a725-4ba6a0e16e26)

**Comment by RealRong** [comment]
链接图标大小这个会改，不过分组可能有难度

**Comment by holduan** [comment]
> 链接图标大小这个会改，不过分组可能有难度

cool，慢慢来 😃
