### ISSUE TITLE
【优化】希望视频实体的音量上限提高到200%

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#237]
现状：
有的视频文件音量本身很小，用软件也增益不了

希望改进：
视频实体的音量上限提高到 200%

![图片](https://github.com/Rendevoz/Rendevoz/assets/139304871/3c7613c9-8187-4da8-bf07-969039db2929)

**Comment by Ihopeyouarehappy** [comment]
类似于potplayer，可以让视频音量超出视频本身，因为部分视频音量太低了，不知为何软件也增益不了，求优化

**Comment by RealRong** [comment]
暂时无法修改音量超过100%
