### ISSUE TITLE
【bug】视频实体中的章节无法跳转

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#238]
现状：
视频实体中增加章节后，会自动新增第一章节，但是自动新增的第一章节无法点击跳转，自己新建的旧可以

希望优化：
第一章节可点击跳转

![20240401_202021](https://github.com/Rendevoz/Rendevoz/assets/139304871/ebd14ac8-fb71-4c4f-bada-4c44e9e47a11)

**Comment by RealRong** [comment]
fixed
