### ISSUE TITLE
【组】【新的小功能】组内实体计数以及数字计数

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#244]
需求：

1. 表格 “新建” 字样改为 本表格内共有多少个实体数量（筛选后），鼠标移动至按钮时则显示 ”新建“字样
2. 新增一个用于计算的属性，用于计算数字属性（这样可以直接用于记账等需要计算的情景了）

![20240402_153026_zip](https://github.com/Rendevoz/Rendevoz/assets/139304871/079feb39-8056-4668-b352-275add9d50d3)
![20240402_153056_zip](https://github.com/Rendevoz/Rendevoz/assets/139304871/c082f2f6-6596-4829-97a3-4d50e908c4d8)
![20240402_153307_zip](https://github.com/Rendevoz/Rendevoz/assets/139304871/435522aa-645e-42de-aa8c-0d3d5809c82e)
![20240402_154123_zip](https://github.com/Rendevoz/Rendevoz/assets/139304871/0a93133c-e43f-4140-a9a2-c0c4f211c297)

**Comment by RealRong** [comment]
这个太复杂了，建议还是用excel来做😓

**Comment by Ihopeyouarehappy** [comment]
请问只是计算和，不计算其他，这样会复杂吗？
另外请问第一点呢，实体数量的显示应该不难？请问可以考虑增加吗
