### ISSUE TITLE
【bug】【编辑器】编辑文本中按回车后出现的bug

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [Rendevoz/Rendevoz#252]
过程：选择多行（跨越块）文本，不删除，直接输入文字，按回车后出bug（具体请看视频）

https://github.com/Rendevoz/Rendevoz/assets/139304871/6ee556e9-062c-47bc-b9da-86d17ccc7774

**Comment by RealRong** [comment]
应该和输入法有关，用mac和windows默认的输入法没这个问题

**Comment by Ihopeyouarehappy** [comment]
我测试了一些输入法
我的系统：win10

微软自带中文输入法：没问题
讯飞输入法：没问题
搜狗输入法：bug
华宇拼音输入法：bug

确实是输入法不同有的会出bug有的不会
