### ISSUE TITLE
【bug】同步块展示异常

### ISSUE THREAD

**Issue by woniuxia** [Rendevoz/Rendevoz#254]
同步块真实内容如下：
![image](https://github.com/Rendevoz/Rendevoz/assets/16383685/56828457-dceb-4559-82d3-4c57607ea62d)

当时嵌入文档后展示如下：
![image](https://github.com/Rendevoz/Rendevoz/assets/16383685/09c8d0e9-955d-4295-9066-e831c4b5833d)

**Comment by RealRong** [comment]
拖入才能显示为同步块，这是行内嵌入
