### ISSUE TITLE
【功能优化】希望对文本卡片可以设置边框及其颜色

### ISSUE THREAD

**Issue by ygli688** [Rendevoz/Rendevoz#271]
![image](https://github.com/Rendevoz/Rendevoz/assets/97214858/9e944328-e38a-40fe-bba4-7fdad3bd118a)
如果技术足够，衍生为每个类型的卡片都可以设置边框颜色就更好了，有时候不太需要整个卡片都变背景，有个框颜色进行区分就好

**Comment by RealRong** [comment]
in progress

**Comment by RealRong** [comment]
supported
