### ISSUE TITLE
【功能优化】嵌入卡片的视频不出现控制栏

### ISSUE THREAD

**Issue by ygli688** [Rendevoz/Rendevoz#281]
![image](https://github.com/Rendevoz/Rendevoz/assets/97214858/7efbd303-28a2-4292-bef6-279566785356)

**Comment by ygli688** [comment]
无论怎么操作都不出现进度条

**Comment by RealRong** [comment]
b站视频如果宽度过短，不会显示控制栏，是b站播放器的问题，没法解决
