### ISSUE TITLE
【功能优化】全局搜索的优化建议

### ISSUE THREAD

**Issue by linyizpx** [Rendevoz/Rendevoz#291]
1.调出全局搜索框，输入要搜索的内容“一箱子水果”。搜索界面如下：
<img width="690" alt="1" src="https://github.com/Rendevoz/Rendevoz/assets/160560187/ff42997f-b717-4984-8469-55180d5f029c">
虽然能够准确定位到“一箱子水果”所在文档，但是，在搜索框没显示“一箱子水果”所在的位置。
然而，点击搜索的的文档进入“第一节收入”，在文档中也没有高亮显示“一箱子水果”所在的位置。
建议是：在搜索界面，能够高亮展示整个词（“一箱子水果”）语所在文档的位置。同时，点击进入之后，能够定位到第一个搜索词的位置，并且高亮展示。
2.全局搜索针对不同文档，有不同的处理结果。
搜索对象1：我新建“11111”文档，在里面输入"胡思乱想"“若初始费用”。如图示：
<img width="717" alt="2" src="https://github.com/Rendevoz/Rendevoz/assets/160560187/7cf336fe-fdd0-46f2-b8cf-5738c56ec2a3">
我通过全局搜索，分别搜索“胡思乱想”“若初始费用”，搜索结果分别如下：
<img width="697" alt="3" src="https://github.com/Rendevoz/Rendevoz/assets/160560187/e8799481-fd31-4f32-8115-b03365ba2163">
<img width="707" alt="4" src="https://github.com/Rendevoz/Rendevoz/assets/160560187/c92deec3-0c7e-4333-bf6d-47348f4acfb6">
上述搜索结果是比较准确的。
搜索对象2：已经建立的文档“第一节收入”，我是通过复制粘贴放入了很多内容，在文档最后，我输入了“胡思乱想”“若初始费用”。
<img width="572" alt="5" src="https://github.com/Rendevoz/Rendevoz/assets/160560187/d9b07092-0f9a-4cfc-a791-f8048a01f377">
然后在通过全局搜索。结果如下：
<img width="587" alt="6" src="https://github.com/Rendevoz/Rendevoz/assets/160560187/df8e57a6-7260-47ab-a519-ce30c6160c19">
搜“胡思乱想”时，搜索结果准确，在“第一节收入”进行了展示。
<img width="611" alt="7" src="https://github.com/Rendevoz/Rendevoz/assets/160560187/6d8c8b40-3b9a-48d4-bb66-cdf1e23eafdd">
而在搜“若初始费用”时，搜索结果“第一节收入”中未展示“若初始费用”的准确结果。
建议是：无论在什么文档里，都要展示所要搜索的不能拆分的词语，并且放在第一搜索顺序。

**Comment by RealRong** [comment]
fixed
