### ISSUE TITLE
【功能优化】组输入标签后，建议自动清空输入内容，方便直接输入下一项内容

### ISSUE THREAD

**Issue by linyizpx** [Rendevoz/Rendevoz#292]
组：输入标签内容后，输入框仍然存在原输入内容，需要手动删除。
建议：按回车选择后，自动清空输入内容，便于直接输入下个内容，不需要再手动删除。

https://github.com/Rendevoz/Rendevoz/assets/160560187/9461c1d1-1ba0-42e0-b489-21ddcf805971

**Comment by RealRong** [comment]
fixed
