### ISSUE TITLE
【BUG】块链接，删除引用的块链接，被引用的原文会被删除

### ISSUE THREAD

**Issue by linyizpx** [Rendevoz/Rendevoz#299]
块链接，删除引用的块链接，被引用的原文会被删除，只能立即通过恢复才能恢复原文，在不知情的情况下，会勿删很多内容，并且无法恢复了。

https://github.com/Rendevoz/Rendevoz/assets/160560187/b6222d1d-df65-4cfa-a122-f7b36cc1e14b

**Comment by RealRong** [comment]
fixed
