### ISSUE TITLE
【BUG】字幕文件无法自动删除

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#312]
虽然此处有个删除,但是
![image](https://github.com/Rendevoz/Rendevoz/assets/95662043/9d6bfa81-3f40-454a-a4bb-42688ccdd6e4)
从这些个文件来看,还是没有删除
![image](https://github.com/Rendevoz/Rendevoz/assets/95662043/4b1455ed-d74e-41c9-8cec-2d204841f84e)

**Comment by RealRong** [comment]
已修复
