### ISSUE TITLE
【BUG】同步块

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#314]
文档1 同步块
文档2 同步块
删除文档1的同步块,文档2同步块的关联实体还是俩个(文档1,文档2)
![image](https://github.com/Rendevoz/Rendevoz/assets/95662043/4f72076b-1e48-4002-be7d-799dc7581f3d)

https://github.com/Rendevoz/Rendevoz/assets/95662043/b7c14eb3-7002-4d34-9ce1-5164d973ad24

**Comment by hype1type** [comment]
![image](https://github.com/Rendevoz/Rendevoz/assets/95662043/633fce54-f94a-436f-8950-143f6e91cf01)
从图片来看,虽然原文的已经没有该同步块了,但是还是关联着.
![image](https://github.com/Rendevoz/Rendevoz/assets/95662043/3d846658-ee1e-4340-8959-12e36bbbdf40)
这个删除含义不是很明确,应该是删除关联或者删除实体或者其他

**Comment by RealRong** [comment]
fixed
