### ISSUE TITLE
【BUG】自动复制导入的文件失效

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#316]
![648bf16c91895f66d75216a5c98349f1](https://github.com/Rendevoz/Rendevoz/assets/95662043/0b1c4ab4-02d2-4ba4-8305-d793a998e5a0)
这两个功能导入文件,遇到无法打开的那种文件比如(.js .py文件),会直接链接到本地文件(哪怕你开启[自动复制导入的文件),左边那个F2功能的还好,有个弹窗能看到文件位置,右边那个**导入文件夹中所有文件**,则只会显示导入成功\失败

删除实体,再清空垃圾站,**会直接删除你本地的文件**

**Comment by RealRong** [comment]
已修复，另外不会删除非复制到文件夹中的的本地文件了
