### ISSUE TITLE
【BUG】重复文件导入bug

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#317]
导入文件的时候遇到重复的文件,也不会提示重复,会直接覆盖?本地文件储存路径files文件里的文件,两个实体链接同一个文件,其中一个实体删除后,另外一个实体打不开文件.这里以pdf为例

**两个实体链接同一个文件**

**Comment by RealRong** [comment]
这不是bug，重复文件就是覆盖掉的，一般情况下不会有两个实体链接一个文件吧

**Comment by hype1type** [comment]
> 这不是bug，重复文件就是覆盖掉的，一般情况下不会有两个实体链接一个文件吧

“一般情况下不会有两个实体链接一个文件吧”，创建实体时，从右侧批量导入那里导入时，会出现俩实体链接一个文件，我的想法是，导入并复制时对文件加个后缀便以区分
