### ISSUE TITLE
【BUG】在组1中通过过滤误添加组1,导致记录无法删除

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#318]
![image](https://github.com/Rendevoz/Rendevoz/assets/95662043/41d6e789-0c85-4c9a-a805-3ea9999605c7)
我通过过滤筛选❓的时候,误将这个组也添加到组里了,导致似乎进入了循环,无法在组中删除这个组
目前我已通过迁移,删除旧实体解决

**Comment by RealRong** [comment]
貌似没这个问题，可以删除啊

**Comment by hype1type** [comment]
> 貌似没这个问题，可以删除啊

很奇怪，issue提出的时候我删除不下10遍，愣是没删除掉（这里指从组中删除）
