### ISSUE TITLE
【功能优化】部分rss 网页打不开,希望调整原网页打开的位置

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#321]
![image](https://github.com/user-attachments/assets/e8d190ff-38ea-495d-9bc7-02baf4317bd5)
![image](https://github.com/user-attachments/assets/8ef6462c-4396-4dbf-84df-fc2a573b9322)

**https://freefilesync.org/news-feed.php**
这个rss 有内容但是解析不出来

**Comment by RealRong** [comment]
Fixed
