### ISSUE TITLE
【BUG】快捷键打开实体信息

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#322]
打开实体信息,到底是以什么为基准的? 初次打开软件,打开一篇pdf,使用快捷键打开实体信息
![image](https://github.com/user-attachments/assets/a89fc4cb-637e-40d2-8e40-195542a53656)
当你手动查看一次信息后,换一篇pdf 使用快捷键查看实体信息,实际上显示的是上次那个信息
![image](https://github.com/user-attachments/assets/95c999b1-aa55-4bdb-8d0d-d730c0ec4df2)
给我一种感觉,就像是有个列表, 查看实体信息就是查看这个列表里面的东西,列表得你手动查看过了才有东西

**Comment by RealRong** [comment]
需要查看过才会显示，快捷键只是打开和关闭
