### ISSUE TITLE
【BUG】通过预览\白板打开于-页面中央的pdf都是无法注释的

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#325]
https://github.com/user-attachments/assets/7eadddc9-4350-43f2-bc55-513037e1d5de

![image](https://github.com/user-attachments/assets/34616057-65f3-458d-8804-fbe4042e1760)
只要在页面中央这种都无法做批注

**Comment by RealRong** [comment]
Fixed
