### ISSUE TITLE
【BUG】重复复现-组内实体相互移动

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#327]
组内实体相互移动,
组A 实体1移动到组B
实体1移动2/3/4次到组B,就会多2/3/4个实体
并且组A内实体还不消失

**Comment by RealRong** [comment]
组内实体之间的移动不会删除其本身

**Comment by hype1type** [comment]
> 组内实体之间的移动不会删除其本身

关于此概念，我觉得 复制到组 能较为贴切，毕竟移动 正常理解就是，旧位置消失，新位置增加
