### ISSUE TITLE
【新功能】为rendevoz提供外部回链

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#331]
像bookxnote pro这样的外链(bookxnotepro://opennote/?nb={b9acf449-cb4c-4fdc-b4d1-c7861ef690cf}&book=e72583f7b166bf8a26f57440e71a4fb9&page=91&x=176&y=140&id=70&uuid=b9b730233f32e09b7f8f18efa4a6f89a)

目前呢。rendevoz提供的导出功能，只能导出文本，无法像其他软件那样导出md等格式，
![image](https://github.com/user-attachments/assets/48e600a0-e072-40bc-96cc-24b789593559)

**Comment by RealRong** [comment]
有外链，在设置，实体与链接里，可以更改为md链接
