### ISSUE TITLE
【bug】组的列表视图-视频实体图片显示

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#333]
![image](https://github.com/user-attachments/assets/026d931a-b9f0-459a-9b6b-fb506ab33dab)
下面几个正方形空白似乎是有图片不显示。
![image](https://github.com/user-attachments/assets/b0ea2e97-35df-450a-97f0-5cf932c11770)
![image](https://github.com/user-attachments/assets/a82a8ce9-7b2f-4de4-90f2-e959f41ae5a1)

**Comment by RealRong** [comment]
这是在线图片，可能网不好或者原图片丢失
