### ISSUE TITLE
【bug】实体的移动

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#343]
组内实体之间的移动不会删除其本身

_Originally posted by @RealRong in https://github.com/Rendevoz/Rendevoz/issues/327#issuecomment-2238855217_

**Comment by hype1type** [comment]
上次说到组内实体相互移动不会删除其本身，但是在此场景下，实在难搞
![QQ_1722308255515](https://github.com/user-attachments/assets/e39ccf5b-812d-4cbe-8be6-77f362fcb936)
![image](https://github.com/user-attachments/assets/46be4c7b-6275-4861-82df-d5694925f766)

我在【博客园】组将【03】 移动到 【书籍】里，但我又想从【书籍】移除 【03】，由于关联这同一实体，我不能选择删除实体，而是选择从组中删除，然而又回到了这个问题，该实体是无法删除的，甚至能在同一个组里共存，请问如何删除呢？
![image](https://github.com/user-attachments/assets/5a0c4481-cb5d-47cd-97b6-8e041a4aa18f)

**Comment by hype1type** [comment]
一删除就全删除了
![image](https://github.com/user-attachments/assets/1695b75a-6f0d-44c8-843d-14b59a576831)

**Comment by hype1type** [comment]
我发现， 当从【书籍】移除 【03】时，【03】会出现在主页，当我点击组【书籍】，原本在主页的【03】会消失，就像分身被合并了一样。很奇怪
组内共存截图
![6eca0d8fdee0514a722d05949c1040e9](https://github.com/user-attachments/assets/30c8b0bf-3b9c-46a8-99be-66f065eef684)

**Comment by RealRong** [comment]
当从书籍中删除时，会将其隐藏改为不隐藏，再次进入其他组会再次设置成隐藏
后面我修改一下吧

**Comment by hype1type** [comment]
> 当从书籍中删除时，会将其隐藏改为不隐藏，再次进入其他组会再次设置成隐藏 后面我修改一下吧

主要对其逻辑/特性不是很明白，故而认为是bug
