### ISSUE TITLE
【bug】网页解析 文本换行问题

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#349]
![image](https://github.com/user-attachments/assets/35178649-ea55-443d-893e-8ff75befa702)
https://english.cctv.com/2024/08/06/ARTIVFDydrdyQHkw3pol3dez240806.shtml?spm=C69523.PREmHITS7XIG.MaHyxoHRqIrX.5
![image](https://github.com/user-attachments/assets/97c63b0f-9125-4483-a419-25e5f75631e9)

https://api.flutter.dev/flutter/animation/animation-library.html
![image](https://github.com/user-attachments/assets/6ecf6c83-44d7-4bdb-b974-9aa3e19d41dd)

图2、3与网页格式基本一致，但是图三解析出来的，一个长句子老会换行

**Comment by RealRong** [comment]
原网页问题，你把whitespace prewrap给p元素加上，一样会换行，它加了很多\n
