### ISSUE TITLE
【优化】文档公式块

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#368]
文档公式块缺少行内公式，只有行间公式，无法 

回忆前面提到的,任何服从方差为  \sigma ^ {2}  的正态分布的随机变量x,kx服从方差为  k^ {2} \sigma ^ {2}  的正态分布。关于这里更细节的解释可以在附录-方差期望的推导中找到。

输入类似上文的含公式片段

**Comment by RealRong** [comment]
有行内公式啊
