### ISSUE TITLE
同一个 pdf 可以打开两份或者多份，这样有利于查找上下文的图表，便于理解顺畅不用来回上下翻

### ISSUE THREAD

**Issue by chonglin9606** [Rendevoz/Rendevoz#37]
<img width="1763" alt="iShot_2023-09-06_19 58 02" src="https://github.com/Rendevoz/Rendevoz/assets/47425135/e458d08f-ee06-4f07-ae3d-f5047b2a2e0f">

**Comment by RealRong** [comment]
设置里可以选择是否允许打开多个同样的文件
