### ISSUE TITLE
【bug】播客america

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#379]
![image](https://github.com/user-attachments/assets/99d5c1df-80d1-4fd2-b7c2-4a1caf908914)
没挂梯子，点进去，出现这个，无法返回
![image](https://github.com/user-attachments/assets/8a3dbdf5-a7b4-411f-b5d7-ee4c9d1cc9ef)
gua'le挂了梯子也这样

**Comment by RealRong** [comment]
貌似没这个问题，先close了
