### ISSUE TITLE
【优化】白板里新建的笔记标题不会自动换行

### ISSUE THREAD

**Issue by JokAlec** [Rendevoz/Rendevoz#38]
![image](https://github.com/Rendevoz/Rendevoz/assets/79049115/2279b38f-5a51-4dbf-a8cb-6315e90abe7e)

**Comment by RealRong** [comment]
![截屏2023-09-09 03 25 08](https://github.com/Rendevoz/Rendevoz/assets/30063889/2d1f3f4f-3d57-401a-82b3-27289098aa26)经测试貌似没这个问题，最好拍个视频复现下
