### ISSUE TITLE
【优化】ai总结大纲

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#382]
1. 点击相关的item，虽然跳转到该页，但是不高亮文本
2. 对大纲item能像对话那里那样添加为笔记

![image](https://github.com/user-attachments/assets/94336e2d-e031-4ebe-a55f-2c0ae20b4401)
![image](https://github.com/user-attachments/assets/c426c500-6b74-4bf2-819c-ee6fdb9245ff)

**Comment by hype1type** [comment]
关于第一个问题，似乎不是不高亮，而是不准

**Comment by hype1type** [comment]
这个问题我找到原因了，ai总结的内容不带[12,14] 所以根本无法定位到原文
![image](https://github.com/user-attachments/assets/5f740dc0-5743-4586-a584-5e2160bc77da)

**Comment by RealRong** [comment]
PDF里面，ai总是不能带上正确的原文，我也没啥办法，只能跳转到页面

**Comment by hype1type** [comment]
> PDF里面，ai总是不能带上正确的原文，我也没啥办法，只能跳转到页面
可不可以迂回一下，ai引用的是 12345678，缺失了9，导致无法跳转，但是我们跳转的时候 只跳转34567，去头去尾，保证准确跳转，毕竟这样能准确定位段落，也好过不高亮，摸不清楚在哪
仅供参考
@RealRong

**Comment by hype1type** [comment]
![image](https://github.com/user-attachments/assets/7c3df1a6-1c25-469d-8883-b885fc267419)
![image](https://github.com/user-attachments/assets/8468f138-dd08-4f72-bac9-7644a042772b)
这个就是不一样的问题了，ai带上了原文，但是只定位了一个can be，上图是错的，下图是对的，但是定位的是上面的那个。
