### ISSUE TITLE
希望优化一下代码部分

### ISSUE THREAD

**Issue by Makingtimefor** [Rendevoz/Rendevoz#384]
在其他平台写的代码完全不能复制进来,
<img width="427" alt="Screenshot 2024-09-08 at 09 49 52" src="https://github.com/user-attachments/assets/de2edb5d-444d-4ab7-9dec-0bd43a872a75">
如是代码复制到对应的代码快输入框中就变成了这样
<img width="631" alt="Screenshot 2024-09-08 at 09 50 56" src="https://github.com/user-attachments/assets/cde8d7d3-9d2e-4074-b785-1708fd0e5a3d">

**Comment by RealRong** [comment]
已修复
