### ISSUE TITLE
自动同步 bug

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#401]
当修改默认存储路径后，并开启自动同步后会出现，
![image](https://github.com/user-attachments/assets/ef16675b-9a40-4f76-bc0e-68c393bc5e71)
![image](https://github.com/user-attachments/assets/190d5a85-8093-4f37-b80b-2813244f1081)
打开一个 pdf 随便点几下，然后所有文件就会出现重新上传下载

**Comment by RealRong** [comment]
应该修复了
