### ISSUE TITLE
【优化】RSS浏览信息时加载速度真慢，别的RSS软件一般只要1-2秒，咱们这经常6-7秒，甚至加载不出来

### ISSUE THREAD

**Issue by lycfeelings** [Rendevoz/Rendevoz#402]
![image](https://github.com/user-attachments/assets/3a976ecd-f144-4939-a095-f2fd09eaf131)

**Comment by RealRong** [comment]
可以选择把设置，网页里默认为简洁模式关了，这样能直接显示原网页，快很多。
加载的慢是为了获取完整网页，不然很多网页没法剪藏

**Comment by lycfeelings** [comment]
确实快很多，6
