### ISSUE TITLE
【BUG】@时，第一个字会有问题

### ISSUE THREAD

**Issue by ygli688** [Rendevoz/Rendevoz#404]
![image](https://github.com/user-attachments/assets/a005dd64-e7c9-448f-8a9e-ccc03a6777b1)

**Comment by RealRong** [comment]
应该修复了

**Comment by ygli688** [comment]
> 应该修复了

![image](https://github.com/user-attachments/assets/a51132d7-8311-44aa-ae55-43b978135e77)
英文没问题，中文依旧存在
