### ISSUE TITLE
【功能优化】搜索结果焦点 

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#405]
![image](https://github.com/user-attachments/assets/982f7505-92c7-4268-bbbe-6d7fe0f3343f)
这个没回答我，我放一个视频看看

https://github.com/user-attachments/assets/be052f37-e85e-4d97-9391-a91f192f7239

回车一直挂在搜索栏上，切换成高亮批注，只要你回车，就会按照搜索栏的顺序 跳转

**Comment by RealRong** [comment]
原来如此，我还以为是全局搜索的问题，已修复
