### ISSUE TITLE
【Bug】数据无故丢失

### ISSUE THREAD

**Issue by haogeek** [Rendevoz/Rendevoz#406]
不知道是不是同步导致的，反正昨天新写的东西，关软件之前执行了推送本地数据和同步文件，然后今天再打开就没了。
看了下数据文件夹里的files，json内容都还在，但是软件里就是看不到，也没有任何途径能够重新导入回软件里，设置里的重建索引也形同虚设，根本没用。

不是，这同步到底要怎么用啊，官方也一丁点儿文档都没有，一个推送一个拉取一个同步文件，我应该先点哪个？
我都终身会员了这让我怎么敢继续用下去啊？能退钱不？

**Comment by haogeek** [comment]
其他缺陷还有一大堆，这软件真的是不敢用了，再怎么着也不能丢数据啊？

* 同步块
    * 白板中的文档稍微一拖动文字就会创建同步块
    * 同步块删除后在知识库里还有
    * 同步块只能包含单个块，不能包含多个块（以及层级化列表）
* 编辑器
    * 撤销操作不可靠
    * 行内格式化比较基础，没有删除线
    * 有序列表在嵌套了无序列表后无法再连续编号
    * 使用/选择块类型后，/未删除
* 搜索
   * 打字过程中的非完整关键字也被计入搜索历史
   * 经常搜不到预期结果
* 文件夹（收藏夹）
   * 删除文件夹没有撤销操作
* 用户体验
    * 没有文档，没有功能提示和指引
    * 订阅说明不够明确，终身版没有AI点数
* 附件
    * 未被引用的附件没有自动或手动清理
* PDF
    * 截图清晰度低

**Comment by hype1type** [comment]
"一个推送一个拉取一个同步文件，我应该先点哪个？"
感觉你是个大笨蛋，当然这个软件的文档确实没有

电脑a关闭后 先推送数据再同步文件
电脑b打开后，先拉取数据再同步文件。
我个人就这样，感觉逻辑挺清楚的

**Comment by hype1type** [comment]
“同步块删除后在知识库里还有”
由于你没说明是哪个场景。我猜测1、你是在白板里删除的 2、你是在主页删除的
这个应该是和实体的理念有关，你只有把垃圾桶里的删除了，他才会消失，否则只是放到垃圾桶里还是会引用，还是会显示

**Comment by hype1type** [comment]
其他你提的，复议，我表示赞同

ai点数这个，不好说，终身版毕竟是一锤子买卖
群主之前建议用自己的或者其他厂商的，我用的deepseek的，送了10块钱的，感觉能用好几个月

**Comment by RealRong** [comment]
同步块可以有多个块，并且你应该只是在白板里删除了，并且拖动文字并不会创建同步块，拖动整个块才会。
PDF截图清晰度应该不低了吧，一个图片都是500kb往上了

**Comment by RealRong** [comment]
导入就是把backup里面的json在设置里面导入啊

**Comment by haogeek** [comment]
> 电脑a关闭后 先推送数据再同步文件
> 电脑b打开后，先拉取数据再同步文件。

我当然知道正确的逻辑就应该是这样，但这样操作的结果是我并没有得到预期的同步效果。

**Comment by haogeek** [comment]
> ai点数这个，不好说，终身版毕竟是一锤子买卖

这个我觉得价格和会员类型划分上都没有问题，但是应该更明确地指出终身版没有AI点数，需要自己配。尤其是官网上写了终身版有“文本翻译和与AI功能”，但实际上使用文本翻译和AI功能时都会提示“AI点数不足”，所以默认这两个功能其实是用不了的，这里没有说明清楚。

**Comment by haogeek** [comment]
> 拖动文字并不会创建同步块，拖动整个块才会

是的我想我应该是拖动的整个块，另外我发现在文档编辑状态下拖动块是重排，这跟大纲笔记和Notion类编辑器的体验是一致的，但到了白板里，同样是编辑文档，拖动就变成了创建同步块，这就给人带来预期之外的效果了。

> 你应该只是在白板里删除了

这个我基本上可以理解了，作为实体，它在其中一个引用处被删除而在库中仍然存在是符合逻辑的。问题在于，“在本页中取消同步”和”删除“一起出现在同步块右键菜单里，是容易产生歧义的，因为删除并没有说明是“在本页中删除”。当一个块成为同步块时，它其实就成为了一个独立实体，而不再归属于它原本所在的实体，这个概念对于从别的笔记软件转来的用户来说是不太习惯的，比如说思源笔记里，同步块其实就是嵌入块，当然也可以自定义锚文本使其成为引用块，但无论引用还是嵌入，都只是指向一个本来就存在的块，而无需新建任何独立的东西，当引用被删除时，那个块还是保留在原有位置，就像什么都没发生过一样，而不是像Rendevoz这样，留在库里成为了一个孤立的实体，甚至当原本的文档被删掉时这个块依然会被保留，即便没有任何地方用到它，这就有点函数副作用的味道了。
![image](https://github.com/user-attachments/assets/2d30c411-4ea2-4c96-b8db-d4b61187dd0e)

> 同步块可以有多个块

新建一个同步块确实可以在其中写入多个块，但通过拖动创建同步块貌似只能拖一个块，我没发现怎么拖多个块。另外，如果是将一个无序列表折叠后进行拖动，则创建出来的同步块无法再对已折叠的列表进行展开，这似乎也是由于该同步块里其实只有列表顶层一个块，而没有列表子项，所以不存在折叠与展开。

> 导入就是把backup里面的json在设置里面导入啊

导入了，但并没有用，我对backup里的每个json进行了尝试，都无法找回丢失的内容，逐个查看backup里的json原始内容，也确实没有我丢失的部分，这说明backup并未有效记录和保护我的数据，大概是因为我设的频率是每天。但我的问题是，我明明可以在files文件夹内的json里发现我丢失的内容，但这些内容既没有被软件自动识别到，我也没办法把它们导回软件（导入files里的json会提示数据类型不对），所以它们留在files里有什么意义呢？

**Comment by haogeek** [comment]
关于截图清晰度，我们来对比一下：

![image](https://github.com/user-attachments/assets/5947516b-77fa-405a-bffd-281e1bd69d50)

我从imgs文件夹找到了这张PDF标注截图，它确实有近500KB，但效果就是这样：

![c46e781860f3f7f1e45707e14c5db95e](https://github.com/user-attachments/assets/aa080cde-289b-4013-b671-4ab780c057b6)

**Comment by RealRong** [comment]
files里的json是文档数据，不是数据库里的数据。
下个版本每5分钟会强制自动导出一份数据，应该没问题了

**Comment by haogeek** [comment]
那现在还是没法恢复丢失的实体了……

另外，同步的时候也会同步backup文件的吧？这样说来，如果同步有问题，或者有冲突，是不是也有可能导致backup被误覆盖？从而导致仍然没有可靠的数据恢复办法？

**Comment by haogeek** [comment]
@RealRong 另外，您还是没有回答我的问题：

> 我明明可以在files文件夹内的json里发现我丢失的内容，但这些内容既没有被软件自动识别到，我也没办法把它们导回软件

我知道files里的是文档数据，那也就意味着我的数据丢失只是因为数据库坏了，那么当前有提供任何办法可以修复数据库吗？既然原始的文档数据还在，为何软件无法识别到呢？

以及，截图清晰度的对比我已经给出来了，这个有什么说法么？
