### ISSUE TITLE
【优化】关于新增问答属性的优化

### ISSUE THREAD

**Issue by hype1type** [Rendevoz/Rendevoz#408]
以下仅个人见解
一是根据我所勾画的图片所示，pdf侧边栏的批注下面，存在问答属性的时候可以显示问题和答案解析，不必再到组里查看，尤其是“问答实体”作为属性时，无法直观的查看，如下图

![8113c9262d6767c395e4867acfb1fab2](https://github.com/user-attachments/assets/2679f766-691e-4505-a3cb-090b9f105447)
![image](https://github.com/user-attachments/assets/fdb40d8f-1c66-47d5-a81f-8f9245fc60ae)

二是组里选项那个打开，如 #363 图片，将问答实体融合在侧边栏

**Comment by RealRong** [comment]
已优化
