### ISSUE TITLE
【优化】代码粘贴没有缩进

### ISSUE THREAD

**Issue by ygli688** [Rendevoz/Rendevoz#411]
![image](https://github.com/user-attachments/assets/88f1b614-b629-47be-8145-31888805fb97)

**Comment by RealRong** [comment]
这是不是直接从IDE里粘贴过来了，好像就是没有缩进的

**Comment by ygli688** [comment]
> 这是不是直接从IDE里粘贴过来了，好像就是没有缩进的

以前的版本粘贴过来是有缩进的，记事本就可以显示缩进
