### ISSUE TITLE
【BUG】高亮标注编辑时可以加粗，回车以后样式消失

### ISSUE THREAD

**Issue by ygli688** [Rendevoz/Rendevoz#412]

**Comment by RealRong** [comment]
啥意思，能给个图片复现不

**Comment by ygli688** [comment]
![image](https://github.com/user-attachments/assets/8808d9b6-a53c-44ae-8394-a1dc7db9e3cc)
刚刚发现，快捷键加粗就会失效，但是手动****就没问题
然后 + - 出现的都是有序列表，不是无序列表

**Comment by hype1type** [comment]
> 刚刚发现，快捷键加粗就会失效，但是手动****就没问题 然后 + - 出现的都是有序列表，不是无序列表

“快捷键加粗” ctrl b 我觉得才是bug，“手动****”  #396 刚加入的
“ + - 出现的都是有序列表，不是无序列表” 我不怎么用，无法评价
