### ISSUE TITLE
【优化】文档中的功能在编辑和阅读模式中打通

### ISSUE THREAD

**Issue by ygli688** [Rendevoz/Rendevoz#413]

**Comment by ygli688** [comment]
虽然有crtl+e，但是在编写时也有解释的需求，阅读时的解释，想要复制到文档中还得切换编辑模式，来回切换很麻烦，希望打通

**Comment by hype1type** [comment]
> 虽然有crtl+e，但是在编写时也有解释的需求，阅读时的解释，想要复制到文档中还得切换编辑模式，来回切换很麻烦，希望打通

实际上上个版本，二者拥有一样的操作，不过在那之后分开了

**Comment by ygli688** [comment]
> > 虽然有crtl+e，但是在编写时也有解释的需求，阅读时的解释，想要复制到文档中还得切换编辑模式，来回切换很麻烦，希望打通
> 
> 实际上上个版本，二者拥有一样的操作，不过在那之后分开了

个人觉得分开不好，希望可以改进，或者自定义按钮，不要的人隐藏就好
