### ISSUE TITLE
【优化&功能请求】视频支持导入 从通义效率导出来的“导读”

### ISSUE THREAD

**Issue by Ting1304** [Rendevoz/Rendevoz#419]
现在视频支持导入字幕，希望大佬可以支持导入 从通义效率导出来的“导读”。通义效率导出来的格式有多种，支持导出为md格式。

“导读”里面有章节、要点回顾、发言总结等，我想可以在这里增加几个Tab
![image](https://github.com/user-attachments/assets/92cd7ab4-26d3-449e-82e8-08065f9b727b)

以下是通义的界面截图
![image](https://github.com/user-attachments/assets/4b4fcbd3-9e4a-4a1d-8618-625724436d01)

**Comment by RealRong** [comment]
有自带的ai总结，需要订阅后使用
