### ISSUE TITLE
视频标注bug

### ISSUE THREAD

**Issue by Elijahcccc** [Rendevoz/Rendevoz#42]
第一次发图跟视频，不知道你看得见不，看不见Q我：萌系小卤蛋或⭐⭐⭐，就是借你云盘的那个

![微信截图_20230910174646](https://github.com/Rendevoz/Rendevoz/assets/144094894/2afbe2dc-e5b8-4db3-836b-b33deb66ea6b)
刚才试了一下b站视频标注，可以正常使用，但是标注在视频中没显示，很受影响

https://github.com/Rendevoz/Rendevoz/assets/144094894/e2517bd3-b9cd-4ec2-9069-64f353d75d58
这个视频，是我打开b站自己购买的课程，它的标注方式很奇怪，无法像上面一样在视频中就能标注，得到视频点一下，才能启用快捷键标注，到视频里面就无法操作

这两个问题希望大大尽快解答解决噢

**Comment by RealRong** [comment]
在线视频使用的是webview相当于另开了一个网页，没办法显示标注或者快捷键，这个是系统限制

**Comment by Elijahcccc** [comment]
了解了，那同样的在线视频，怎么会出现一个可以在视频内标注，另一个却得在视频外才能标注呢

**Comment by RealRong** [comment]
网盘的在线视频不是另开一个网页，还是在软件内完成的，不过youtube和b站是开另一个网页，两者虽然都是在线视频但实现方式上不一样
