### ISSUE TITLE
【功能优化】白板设置 允许在相连时自动为实体添加链接

### ISSUE THREAD

**Issue by KuiyueRO** [Rendevoz/Rendevoz#68]
请添加一个子选项

勾选添加链接时，可以选择同步白板label到关系图和属性面板

**Comment by RealRong** [comment]
在设置，组件，白板里有设置

**Comment by KuiyueRO** [comment]
emm指的是同步白板连线上的label，将它同步到实体信息和图谱中。希望开发者大大考虑一下
