### ISSUE TITLE
【新功能需求】字幕浏览器文章视图+高亮+自动滚动

### ISSUE THREAD

**Issue by holduan** [Rendevoz/Rendevoz#7]
如题

https://github.com/Rendevoz/Rendevoz/assets/80377040/0bd633a7-ac58-4985-96ed-96b880f25223

**Comment by chonglin9606** [comment]
https://github.com/Rendevoz/Rendevoz/assets/47425135/8e1a1fe0-43fc-4c2b-90f0-f7bc6232a19e

 +1，另外再说一下现有的视频字幕，把字幕框开到最大并不能显示全部的字，如下面视频所示，拥有文章视图字幕方便对视频内容进行高亮，避免了再看一遍视频某个视频。

**Comment by holduan** [comment]
【新功能需求】字幕浏览器排版：**字幕时间码** 跟 **字幕内容** 放同一行
