### ISSUE TITLE
【BUG】阅读模式和编辑模式部分行间距不一致

### ISSUE THREAD

**Issue by KuiyueRO** [Rendevoz/Rendevoz#83]
主要表现在无序列表和行内标题上

**Comment by RealRong** [comment]
可以发个图片举例一下

**Comment by KuiyueRO** [comment]
编辑模式

![image](https://github.com/Rendevoz/Rendevoz/assets/63145205/5b8bd6ad-48e1-4d55-9ee6-f7f36d77f891)

阅读模式

![image](https://github.com/Rendevoz/Rendevoz/assets/63145205/579e9910-3aca-49af-bf63-a5fbcf2c6a9c)

**Comment by RealRong** [comment]
阅读模式行间距就是设计的比编辑模式大一些

**Comment by KuiyueRO** [comment]
上方截图是已经在`设置 > 编辑器 > 行距` 中调节一致后截的图。

因为Rendevoz本身就可以分别调节编辑模式和阅读模式的间距，是不是不用特意区分间距呢？
