### ISSUE TITLE
[bug] 删除收藏文件夹时报错

### ISSUE THREAD

**Issue by curlykay** [Rendevoz/Rendevoz#85]
### 问题描述
删除当前标签页正在显示的收藏文件夹时，会抛出错误
<img width="1091" alt="image" src="https://github.com/Rendevoz/Rendevoz/assets/35558285/eb525468-aff5-4181-88d8-79e582f76549">

<img width="1271" alt="image" src="https://github.com/Rendevoz/Rendevoz/assets/35558285/86cd88ca-9b56-4173-91bf-c4557c59b0ef">

### 期望效果
如果删除的是当前聚焦的收藏夹标签页，可以重新聚焦至其他已打开的标签页，或者回到（打开）主页

**Comment by muhanstudio** [comment]
同样期望修复
