### ISSUE TITLE
[功能优化]对markdown语法和实时预览的完整支持

### ISSUE THREAD

**Issue by curlykay** [Rendevoz/Rendevoz#90]
现在体验对于markdown
对于markdown标题段落和列表等支持实时预览的书写方式
对于代码块只支持` / `选择，不支持使用` ``` `自动添加
不支持粗体、斜体语法等。

Rendevoz将会有对markdown语法和实时预览的完整支持吗？

**Comment by RealRong** [comment]
做起来比较麻烦，短期内不会支持
