### ISSUE TITLE
【Bug】按下「/」键后，有时会出现「//」或者「/、」，应该是软件的 / 命令的问题

### ISSUE THREAD

**Issue by edward-kyle** [Rendevoz/Rendevoz#93]
![image](https://github.com/Rendevoz/Rendevoz/assets/78415230/afbfad24-306c-4105-9580-738d24f51368)
如上图所示

使用微软拼音输入法或者英文键盘都不会发生这类bug

**Comment by edward-kyle** [comment]
小狼毫输入法是一个开源、可自定义配置的输入法。因为可以做到「有什么输入需求就自己在里面编程配置」，所以很多人会使用。

我已经通过修改输入「/」键的配置解决了这个问题，开发者大大可以关闭这个issue了。

**Comment by edward-kyle** [comment]
我来说一下解决办法：
小狼毫输入法在「拼音输入模式」中，按下「/」，会出现两个 / 符号，在「英文输入模式」下，只会出现一个 / 符号。

以下是我的「拼音输入模式」下的半角符号设置：
![42b5d8204d288ae6f94772577f31ca77](https://github.com/Rendevoz/Rendevoz/assets/78415230/43a2e543-9095-4ad5-9b7e-0748ab332aad)

里面原本是有一行这样的：
‘/’ : '/'

我把这一行删除，就解决问题了。

问题解决后，按下「/」按键，屏幕上就只会出现一个 / 符号。

**Comment by edward-kyle** [comment]
看到群里有用户使用微软输入法，在捷指令输入/会变成 /、 。
应该是输入 / 上，有什么bug，开发者大大还是再看看怎么改这个bug吧。

**Comment by edward-kyle** [comment]
关联 #178

**Comment by RealRong** [comment]
使用英文输入法，或者关闭输入法的中文标点。
微软输入法解决方式：https://answers.microsoft.com/zh-hans/windows/forum/all/%E4%B8%BA%E4%BD%95%E5%BE%AE%E8%BD%AF%E6%8B%BC/3ba1253e-d58f-45b3-9731-da32205264c4
